=== litchie/exult-ios/exult/trunk/docs/readme/readme.dtd
<!-- block and inline elements -->

<!ENTITY % inline "br|em|extref|Exult|kbd|key|q|ref|strong|ref1|ref2|Studio" >

<!ENTITY % lists "ul|ol" >

<!ENTITY % block "cite|configdesc|keytable|para|%lists;" >


<!-- ****************** elements ****************** -->
<!ELEMENT readme (section*)>
<!ELEMENT section (sub*)>
<!ELEMENT sub (header, body)>
<!ELEMENT header (#PCDATA|Exult)*>
<!ELEMENT body ( #PCDATA | %block; )*>

<!ELEMENT para ( #PCDATA | %inline; )*>
<!ELEMENT cite (#PCDATA|para|q)*>
<!ELEMENT q (#PCDATA)>
<!ELEMENT ol (li*)>
<!ELEMENT ul (li*)>
<!ELEMENT li ( #PCDATA | %inline; )*>

<!ELEMENT key (#PCDATA)>
<!ELEMENT kbd (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>

<!ELEMENT ref (#PCDATA)>
<!ELEMENT ref1 (#PCDATA)>
<!ELEMENT ref2 (#PCDATA)>
<!ELEMENT extref (#PCDATA)>

<!-- Empty elements -->
<!ELEMENT br (#PCDATA)>
<!ELEMENT Exult (#PCDATA)>
<!ELEMENT Studio (#PCDATA)>

<!ELEMENT configdesc (line*)>
<!ELEMENT line (#PCDATA|comment)*>
<!ELEMENT comment (#PCDATA|ref|key|q)*>

<!ELEMENT keytable (keydesc*)>
<!ELEMENT keydesc (#PCDATA|Studio)*>

<!-- ****************** attributes ****************** -->
<!ATTLIST	readme		title	CDATA	#REQUIRED>
<!ATTLIST	readme		changed	CDATA	"">
<!ATTLIST	section		title	CDATA	#REQUIRED>

<!ATTLIST	sub		name	CDATA	"">
<!ATTLIST	cite		name	CDATA	"">
<!ATTLIST	keytable	title	CDATA	#REQUIRED>
<!ATTLIST	keydesc		name	CDATA	"">

<!ATTLIST	ref		target	CDATA	#REQUIRED>
<!ATTLIST	ref1		target	CDATA	#REQUIRED>
<!ATTLIST	ref2		target	CDATA	#REQUIRED>
<!ATTLIST	extref		target	CDATA	#REQUIRED>

=== litchie/exult-ios/exult/trunk/docs/readme/readme.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE readme SYSTEM "readme.dtd">
<readme title="Exult" changed="03 Septembre 2001(GMT)">
	<section title="Introduction">
		<sub name="whatis_exult">
			<header>What is <Exult/>?</header>
			<body>
				<para>
					Ultima 7, an RPG from the early 1990's, still has a huge following. But,
					being a DOS game with a very non-standard memory manager, it is difficult
					to run it on the latest computers. <Exult/> is a project to create
					an Ultima 7 game engine that runs on modern operating systems, capable of
					using the data and graphics files that come with the game.
				</para>
				<para>
					<Exult/> is being developed in C++ under Linux, MacOS and Windows
					using the SDL library to make porting to other platforms relatively easy.
					The current version supports much of the game's plot, allowing you to
					talk to NPCs, use items, solve quests, and even fight monsters. Music,
					speech, and the full introduction are also implemented. This, and further
					development, is only possible due to the work done by other fans who have
					decoded the various Ultima 7 data files, especially Gary Thompson, Maxim
					Shatskih, Jakob Shonberg, and Wouter Dijkslag.
				</para>
				<para>
					<Exult/> aims to let those people who own Ultima 7 (copyright 1993)
					play the game on modern hardware, in as close to (or perhaps even surpassing)
					its original splendor as is possible. You need to <strong>own</strong>
					"Ultima 7: The Black Gate" in order to use <Exult/>, and we encourage
					you to buy a legal copy.
				</para>
			</body>
		</sub>
	</section>	
	<section title="Configurations">
		<sub name="installation">
			<header>Installation</header>
			<body>
				<ul>
					<li>First you need to get Ultima 7. Either you own it already, or
						you buy it somewhere. Then you must install it on a DOS/Windows
						machine to get the data files.<br/>
						Alternatively  you can use a PC emulator to install it. 
						The <strong>Ultima Collection</strong> already contains a pre-installed
						version of U7 (in the directory /ultima7 on the CD).</li>
					<li>From the Ultima7 folder on your PC, copy the STATIC sub folder to 
						an appropiate folder - see <ref target="path_config"/> what those 
						could be.</li>
					<li>Now run <strong>exult</strong> (<strong>exult.exe</strong> in Windows)
						and quit it immediately.</li>
					<li>Edit the configuration file with the correct paths for the game 
						folders and sfx files - see <ref target="exult_config"/></li>
					<li>Run <strong>exult</strong> and enjoy the game :-)</li>
				</ul>
				<para>
					<strong>Word of advice:</strong> Don't mix the files from BG and SI.
				</para>
				<para>
					<strong>Important:</strong> Do not run <Exult/> on an origina Ultima7
					game which you're actually in the middle of playing, as Exult's saved
					files have a different format. There is no way to convert those 
					original savegames and they will just crash <Exult/>.
				</para>
			</body>
		</sub>
		<sub name="exult_config">
			<header>Settings in exult.cfg</header>
			<body>
				<para>
					<Exult/> keeps a configuration file. You can specify where your Ultima 7
					installation is, whether you want full-screen graphics, or windowed, and
					midi devices and midi settings. Some of these options can be set from the
					<strong>Setup</strong> menu when you run <Exult/> or via the Game menu.
				</para>
				<para>
					If you do not already have a configuration file, <Exult/> will make one for you
					filling in sensible defaults by itself. The location of this file varies 
					slightly. On unix systems you can expect to find it in $HOME/.exult.cfg while 
					other operating systems will probably locate it as 'exult.cfg' in the same 
					directory as the <Exult/> binary. However it is recommended that you edit this 
					file by hand to achieve optimal results for your system.
				</para>
				<para>
					The file uses a simple hierarchical XML-like syntax, which should be simple to
					understand and modify. Take care though. Handling of syntax errors in this file
					is not well tested.
				</para>
				<para>
					Okay, the default file looks like this (do not copy the **and following
					- these are my remarks).
				</para>
				<para>
					Note: yes means enabled, no means disabled
				</para>
				<configdesc>
					<line>&lt;config&gt;</line>
					<line>&lt;disk&gt;
						<comment>**see <ref target="path_config"/> for pathsettings</comment></line>
					<line>&lt;data_path&gt;</line>
					<line>data</line>
					<line>&lt;/data_path&gt;</line>
					<line>&lt;game&gt;</line>
					<line>&lt;blackgate&gt;</line>
					<line>&lt;path&gt;</line>
					<line>./blackgate</line>
					<line>&lt;/path&gt;</line>
					<line>&lt;title&gt;</line>
					<line>blackgate</line>
					<line>&lt;/title&gt;</line>
					<line>&lt;keys&gt;</line>
					<line>(default)
						<comment>**configure custom keybindings or leave the (default)
						- see <ref target="exult_keys"/></comment></line>
					<line>&lt;/keys&gt;</line>
					<line>&lt;waves&gt;</line>
					<line>./data/jmsfx.flx
						<comment>**optional setting see <ref target="wave_sfx"/> for 
						configuration</comment></line>
					<line>&lt;/waves&gt;</line>
					<line>&lt;/blackgate&gt;</line>
					<line>&lt;serpentisle&gt;</line>
					<line>&lt;path&gt;</line>
					<line>./serpentisle</line>
					<line>&lt;/path&gt;</line>
					<line>&lt;keys&gt;</line>
					<line>(default)</line>
					<line>&lt;/keys&gt;</line>
					<line>&lt;waves&gt;</line>
					<line>./data/jmsisfx.flx
						<comment>**optional setting see <ref target="wave_sfx"/> for 
						configuration</comment></line>
					<line>&lt;/waves&gt;</line>
					<line>&lt;/serpentisle&gt;</line>
					<line>&lt;/game&gt;</line>
					<line>&lt;/disk&gt;</line>
					<line>&lt;debug&gt;</line>
					<line>&lt;trace&gt;</line>
					<line>&lt;usecode&gt;</line>
					<line>no
						<comment>**enable/disable usecode-tracing for debuging (you 
						shouldn't need this one)</comment></line>
					<line>&lt;/usecode&gt;</line>
					<line>&lt;/trace&gt;</line>
					<line>&lt;/debug&gt;</line>
					<line>&lt;gameplay&gt;</line>
					<line>&lt;double_click_closes_gumps&gt;</line>
					<line>yes
						<comment>**doesn't need an explanation, right?</comment></line>
					<line>&lt;double_click_closes_gumps&gt;</line>
					<line>&lt;cheat&gt;</line>
					<line>yes
						<comment>**enable/disable cheats for that</comment></line>
					<line>&lt;/cheat&gt;</line>
					<line>&lt;skip_intro&gt;</line>
					<line>no
						<comment>**this skips the intro in BG when you started a new game; Iolo talks to
						Peter, the Avatar appears, Iolo talks to you, the mayor talks to you and so on.</comment></line>
					<line>&lt;/skip_intro&gt;</line>
					<line>&lt;skip_splash&gt;</line>
					<line>no
						<comment>**this skips the splash screen, the intro before you get to the
						game menu, disabling it brings you straight to the game menu</comment></line>
					<line>&lt;/skip_splash&gt;</line>
					<line>&lt;/gameplay&gt;</line>
					<line>&lt;audio&gt;</line>
					<line>&lt;enabled&gt;</line>
					<line>yes
						<comment>**enable/disable all audio - this takes precedence over the 
						other audio settings (you can change this in game via
						<key>Esc</key> - the setting is saved)</comment></line>
					<line>&lt;/enabled&gt;</line>
					<line>&lt;effects&gt;</line>
					<line>&lt;enabled&gt;</line>
					<line>yes
						<comment>**enable/disable sound effects (you can change this in game via
						<key>Esc</key> - the setting is saved)</comment></line>
					<line>&lt;/enabled&gt;</line>
					<line>&lt;/effects&gt;</line>
					<line>&lt;midi&gt;</line>
					<line>&lt;enabled&gt;</line>
					<line>yes
						<comment>**enable/disable MIDI effects (you can change this in game via
						<key>Esc</key> - the setting is saved)</comment></line>
					<line>&lt;/enabled&gt;</line>
					<line>&lt;convert&gt;</line>
					<line>gm
						<comment>**see <ref target="music"/></comment></line>
					<line>&lt;/convert&gt;</line>
					<line>&lt;volume_curve&gt;</line>
   					<line>1.000000
   						<comment>**set volume (kind of at least, best don't change)</comment></line>
   					<line>&lt;/volume_curve&gt;</line>
   					<line>&lt;win32_device&gt;</line>
   					<line>-1
   						<comment>**choose the Windows MIDI Device. See <ref target="win32_device"/></comment></line>
   					<line>&lt;/win32_device&gt;</line>
					<line>&lt;/midi&gt;</line>
					<line>&lt;speech&gt;</line>
					<line>&lt;enabled&gt;</line>
					<line>yes
						<comment>**enable/disable speech (you can change this in game via
						<key>Esc</key> - the setting is saved)</comment></line>
					<line>&lt;/enabled&gt;</line>
					<line>&lt;/speech&gt;</line>
					<line>&lt;/audio&gt;</line>
					<line>&lt;video&gt;</line>
					<line>&lt;width&gt;</line>
					<line>320
						<comment>**here you choose your resolution, it can be as big as your
						monitor allows. 320x200 is the resolution of the original.</comment></line>
					<line>&lt;/width&gt;</line>
					<line>&lt;height&gt;</line>
					<line>200</line>
					<line>&lt;/height&gt;</line>
					<line>&lt;scale&gt;</line>
					<line>2
						<comment>**2 enables / 1 disables scaling, some scalers support higher values.
						See <ref target="scaler"/>.</comment></line>
					<line>&lt;/scale&gt;</line>
					<line>&lt;fullscreen&gt;</line>
					<line>yes
						<comment>**do you want to play fullscreen?</comment></line>
					<line>&lt;/fullscreen&gt;</line>
					<line>&lt;disable_fades&gt;</line>
					<line>no
						<comment>**"no" enables fading between different menu points</comment></line>
					<line>&lt;/disable_fades&gt;</line>
					<line>&lt;scale_method&gt;</line>
					<line>SuperEagle
						<comment>**choose different scalers here - see <ref target="scaler"/></comment></line>
					<line>&lt;/scale_method&gt;</line>
