=== litchie/exult-ios/exult/trunk/docs/xml/docs.dtd
<!-- block and inline elements -->

<!ENTITY % inline "#PCDATA|br|em|extref|Exult|kbd|key|q|ref|ref1|section_ref|strong|Studio|Pentagram|img" >

<!ENTITY % lists "ul|ol" >

<!ENTITY % block "cite|configdesc|keytable|para|%lists;" >


<!-- ****************** elements ****************** -->
<!ELEMENT faqs (section*)>
<!ELEMENT readme (section*)>
<!ELEMENT studiodoc (section*)>
<!ELEMENT section (sub*)>
<!ELEMENT sub (header, body)>
<!ELEMENT header (#PCDATA|Exult|Studio|Pentagram)*>
<!ELEMENT body (%block;)*>

<!ELEMENT para ( %inline; )*>
<!ELEMENT cite ( %inline; )*>
<!ELEMENT ol (li*)>
<!ELEMENT ul (li*)>
<!ELEMENT li ( %inline; )*>

<!ELEMENT key (#PCDATA)>
<!ELEMENT kbd (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>

<!ELEMENT ref (#PCDATA)>
<!ELEMENT ref1 (#PCDATA)>
<!ELEMENT section_ref (#PCDATA)>
<!ELEMENT extref (#PCDATA)>

<!ELEMENT img (#PCDATA)>

<!ELEMENT q (#PCDATA)>

<!-- Empty elements -->
<!ELEMENT br (#PCDATA)>
<!ELEMENT Exult (#PCDATA)>
<!ELEMENT Studio (#PCDATA)>
<!ELEMENT Pentagram (#PCDATA)>

<!ELEMENT configdesc (configtag*)>
<!ELEMENT comment (#PCDATA|ref|key|q|Exult|extref)*>
<!ELEMENT configtag (#PCDATA|configtag|manual|comment)*>

<!ELEMENT keytable (keydesc*)>
<!ELEMENT keydesc (#PCDATA)>

<!-- ****************** attributes ****************** -->
<!ATTLIST	faqs		title	CDATA	#REQUIRED>
<!ATTLIST	faqs		changed	CDATA	"">
<!ATTLIST	readme		title	CDATA	#REQUIRED>
<!ATTLIST	readme		changed	CDATA	"">
<!ATTLIST	studiodoc		title	CDATA	#REQUIRED>
<!ATTLIST	studiodoc		changed	CDATA	"">
<!ATTLIST	section		title	CDATA	#REQUIRED>

<!ATTLIST	sub		name	CDATA	"">
<!ATTLIST	cite		name	CDATA	"">
<!ATTLIST	keytable	title	CDATA	#REQUIRED>
<!ATTLIST	keydesc		name	CDATA	"">

<!ATTLIST	ref		target	CDATA	#REQUIRED>
<!ATTLIST	ref1		target	CDATA	#REQUIRED>
<!ATTLIST	section_ref		target	CDATA	#REQUIRED>
<!ATTLIST	extref		target	CDATA	#REQUIRED>
<!ATTLIST	extref		doc	(faq|docs|studio)	#IMPLIED>
<!ATTLIST	img		src 	CDATA	#REQUIRED>
<!ATTLIST	img		alt 	CDATA	#REQUIRED>

<!ATTLIST	configtag	name	CDATA	#REQUIRED>
<!ATTLIST	configtag	manual	(true|false)	"true">
<!ATTLIST	configtag	closing-tag (yes|no) "yes">

=== litchie/exult-ios/exult/trunk/docs/xml/faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE faqs SYSTEM "docs.dtd">
<faqs title="Exult" changed="7 March 2002(GMT)">
	<section title="Changes to the FAQ">
		<sub name="07032002">
			<header>- 7 March 2002</header>
			<body>
				<ul>
				<li><ref1 target="pentagram"/> rewritten a bit.</li>
				<li><ref1 target="virtue_stones"/> this comes up from time to time.</li>				
				<li><ref1 target="paperdoll_issues"/> Why Sparks Paperdoll looks odd.</li>				
				<li><ref1 target="need_to_run"/> runs on Win32 now.</li>
				<li><ref1 target="port_platforms"/> also noted that it runs on Win32.</li>				
				<li><ref1 target="how_to_run"/> some notes on Win32 mode.</li>
				<li><ref1 target="bug_report"/> Cookies need to be enabled to attach savegames.</li>
				<li><ref1 target="by_design"/> combat difficulty option mentioned and linked.</li>				
				<li><ref1 target="known_issues"/> Alternate SI intro is fully working now and 
					force_waveout is now default.</li>
													
				</ul>
			</body>
		</sub>
		<sub name="10012002">
			<header>- 10 January 2002</header>
			<body>
				<ul>
				<li><ref1 target="walkthroughs"/> updated changed links.</li>
				<li><ref1 target="si_ext_intro"/> this gets asked from time to time.</li>
				<li><ref1 target="need_to_run"/> libglade needed as well.</li>				
				<li><ref1 target="how_to_run"/> You need to have cheats enabled.</li>
				<li><ref1 target="bug_report"/> Added a screenshot of the upload checkbox.</li>				
				</ul>
			</body>
		</sub>
		<sub name="07012002">
			<header>- 07 January 2002</header>
			<body>
				<ul>
				<li><ref1 target="pentagram"/> some information on the U8 shapes/map viewer.</li>				
				<li><ref1 target="whereis_exult"/> added link to AmigaOS/MorphOS port.</li>
				<li><ref1 target="what_platforms"/> updated with AmigaOS/MorphOS port.</li>
				<li><ref1 target="u7_versions"/> Spanish SI version.</li>					
				<li><ref1 target="choppy_game"/> some help for people that have choppy gameplay.</li>
				<li><ref1 target="no_sfx"/> people still ask so this should be in the FAQ.</li>
				<li><ref1 target="diferent_volume"/> added.</li>
				<li><ref1 target="paperdoll_issues"/> some issues with the Paperdolls.</li>
				<li><ref2 target="Exult Studio"/> too many changes to list. A must read.</li>
				<li><ref1 target="by_design"/> looping music explained.</li>
				<li><ref1 target="known_issues"/> Neither speech nor subtitles in SI-Endgame.
					Also possible <strong>workaround</strong> for sound issues on Windows.</li>
				<li><ref1 target="compile_issues"/> Max is working to make <Exult/> compile on OSX.
					Don't forget the exult*.flx files</li>												
				</ul>
			</body>
		</sub>

	</section>
	<section title="Introduction">
		<sub name="why_name_exult">
			<header>Why is it called <Exult/> - what is the meaning of this name?</header>
			<body>
				<cite name="Jeff wrote on the Boards">
					I originally wrote it [Exult] solely for X-windows, so that's where
					the 'X' comes from. The "ult", of course, comes from Ultima. It
					was only about 6 months ago [02/29/2000] that I replaced the X code with SDL,
					which is multiplatform. Then Arthuris ported it to Win32 (and to
					BeOS). He had also ported the earlier version, but it was much harder
					to maintain that way.
				</cite>
				<cite name="Ibrahim Holtzmann">
					I'd like to point out that "exult" is also an English verb that
					means "to rejoice, to exhibit great happiness".
				</cite>
			</body>
		</sub>
		<sub name="is_exult_free">
			<header>Is <Exult/> free ?</header>
			<body>
				<para>
					<Exult/> is more than free: it's Free (notice the caps). <Exult/> is released
					under the GNU GPL (General Public License). This means that the source code
					for <Exult/> is freely available and you can do whatever you want with it.
					However, if you make modifications to any of <Exult/>'s components and publicly
					redistribute your work you are required to make the source freely available
					in turn. Obviously the <Exult/> team would be very grateful if any
					modifications you make are contributed back to the main code, so that
					everyone can benefit from them. If you want to work on <Exult/> just send an
					e-mail to the 
					<extref target="mailto:exult-general@lists.sourceforge.net">team</extref>.<br/>
 					More information on the GNU GPL at 
 					<extref target="http://www.gnu.org/copyleft/gpl.html"/>.
				</para>
			</body>
		</sub>
		<sub name="origin_exult">
			<header>Does Origin support <Exult/>?</header>
			<body>
				<para>
					First of all, Origin has been owned by EA for a long time now and from recent 
					developments it seems that Origin only exists now to maintain Ultima Online. 
					Furthermore, Origin and/or people that worked for Origin claim that the source 
					code for Ultima 7 (BG/SI) has been lost for some time.
					So there is no chance for the <Exult/> team to have a look at the actual code.
				</para>
				<para>
					Also the team tried to contact some people from Origin earlier but got no positive
					or negative response on the <Exult/> project. So far it seems that both Origin and 
					EA have decided to ignore <Exult/>.
				</para>
				<para>
					On the other hand former Origin employees contacted the team and congratulated the 
					team on their effort. Most noticeable are Lord British himself and Ken Demarest 
					(Programming Manager of Ultima 7)(hint:spell his name backwards).
				</para>
			</body>
		</sub>
		<sub name="other_ultimas">
			<header>Will <Exult/> support other Ultimas?</header>
			<body>
				<para>
					<Exult/> supports only Ultima 7 (BG/SI and the add-ons). It will never support
					any other Ultima nor do members of the team plan to develop something similar.
					The reasons for this are that no other Ultima is similar to Ultima 7 in the 
					internal workings and also the team used to be quite sick of reverse engineering 
					a game already. 
				</para>
			</body>
		</sub>
		<sub name="pentagram">
			<header>But isn't <Pentagram/> some kind of <Exult/> for U8?</header>
			<body>
				<para>
					<Pentagram/> is a pet project by some members of the <Exult/>team (currently mostly 
					Willem, Colourless, Fingolfin and Darke). It is a <strong>map and shapes viewer</strong> 
					and nothing more (although the team does indeed invest some time to disassemble the Usecode 
					of U8). It isn't meant to be something similar to <Exult/>. It is rather a clever plan
					to stir up interest in other coders to carry this basic work further.<br/>
					Any <strong>developer</strong> is welcome to take a look and contact us.
				</para>
			</body>
		</sub>
		<sub name="multiplayer">
			<header>Will there be a multiplayer <Exult/>?</header>
			<body>
				<para>
					No.
				</para>
				<cite name="Jeff on the Forum">
					The question is 'why?'. I continue working on <Exult/>, in large part, because 
					nobody makes games like Ultima7 anymore. While I think a multiplayer game 
					would be technically interesting, I don't see the need. There are <em>lots</em> 
					of them already, and many experienced people working on new ones.
				</cite>
				<para>
					Note however that <Exult/> is open source. If you want a multiplayer U7 no one
					holds you back to code it in. 
				</para>
			</body>
		</sub>
		<sub name="whereis_exult">
			<header>Where do I find <Exult/>?</header>
			<body>
				<para>
					The latest official version is found on <extref target="http://exult.sourceforge.net/"/><br/>
					Daily snapshots (by Travis Howell) of the Win32 binary and of the CVS source tree can be found at
					<extref target="http://exult.sourceforge.net/download.php"/>.<br/>
					A BeOS binary snapshot can be found at 
					<extref target="http://digilander.iol.it/burton666/exult-beos.zip"/>. Jack Burton provides
					this weekly or whenever it compiles for him. Thanks!<br/>
					There is also a version available for AmigaOS/MorphOS at
					<extref target="http://www.muenster.de/~tomjoad/exult.html"/>. Please see
					<ref target="what_platforms"/> for some more information on this port. 
				</para>
			</body>
		</sub>
		<sub name="whatis_snapshot">
			<header>What is a snapshot? Are these screenshots or what?</header>
			<body>
			    <para>
			    	Bugs and not yet implemented features in <Exult/> get fixed almost daily in the code.
			    	A release is very time consuming that's why there are so few.
			    </para>	
			    <para>
					The snapshot is the newest source code of the program. It is updated almost
					daily, sometimes twice a day. There is information on how to build your
					own binary in the source but there is also the newest pre-compiled Windows executable.
					If you there is no new one this means that either there were no changes to the code
					or the source failed to compile.
				</para>
				<para>
					Also this FAQ mainly addresses the snapshots as people use them and ask question.
					And all the new features and improvements are found in those!
				</para>
			</body>
		</sub>
		<sub name="compile_snapshot">
			<header>How do I compile a source code snapshot for my OS?</header>
			<body>
				<para>
					The source code snapshots contain a file called "README.OS" (like Readme.win32, 
					Readme.MacOS) that explains everything.
				</para>
			</body>
		</sub>
		<sub name="latest_version">
			<header>What is the latest version of <Exult/>?</header>
			<body>
				<para>
					The current official release is V0.96 Beta1. See also <ref target="whereis_exult"/>
					to learn where to get the latest version.
				</para>
				<para>
					To find out which version you are running, press <key>v</key> while in game.
				</para>
			</body>
		</sub>
		<sub name="what_platforms">
			<header>On what platform does <Exult/> run?</header>
			<body>
				<para>
					<Exult/> should be able to be compiled (with minor modifications) on
