=== litchie/exult-ios/exult/tags/Release0_93Alpha4/docs/faq/faqs.dtd
<!-- block and inline elements -->

<!ENTITY % inline "br|em|extref|Exult|kbd|key|q|ref|strong" >

<!ENTITY % lists "ul|ol" >

<!ENTITY % block "cite|configdesc|keytable|para|%lists;" >


<!-- ****************** elements ****************** -->
<!ELEMENT faqs (section*)>
<!ELEMENT section (faq*)>
<!ELEMENT faq (question, answer)>
<!ELEMENT question (#PCDATA|Exult)*>
<!ELEMENT answer ( #PCDATA | %block; )*>

<!ELEMENT para ( #PCDATA | %inline; )*>
<!ELEMENT cite (#PCDATA|para|q)*>
<!ELEMENT q (#PCDATA)>
<!ELEMENT ol (li*)>
<!ELEMENT ul (li*)>
<!ELEMENT li ( #PCDATA | %inline; )*>

<!ELEMENT key (#PCDATA)>
<!ELEMENT kbd (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)>

<!ELEMENT ref (#PCDATA)>
<!ELEMENT extref (#PCDATA)>

<!-- Empty elements -->
<!ELEMENT br (#PCDATA)>
<!ELEMENT Exult (#PCDATA)>
<!ELEMENT Studio (#PCDATA)>

<!ELEMENT configdesc (line*)>
<!ELEMENT line (#PCDATA|comment)*>
<!ELEMENT comment (#PCDATA|ref|key|q)*>

<!ELEMENT keytable (keydesc*)>
<!ELEMENT keydesc (#PCDATA)>

<!-- ****************** attributes ****************** -->
<!ATTLIST	faqs		title	CDATA	#REQUIRED>
<!ATTLIST	faqs		changed	CDATA	"">
<!ATTLIST	section		title	CDATA	#REQUIRED>

<!ATTLIST	faq		name	CDATA	"">
<!ATTLIST	cite		name	CDATA	"">
<!ATTLIST	keytable	title	CDATA	#REQUIRED>
<!ATTLIST	keydesc		name	CDATA	"">

<!ATTLIST	ref		target	CDATA	#REQUIRED>
<!ATTLIST	extref		target	CDATA	#REQUIRED>

=== litchie/exult-ios/docs/faq/exult_faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE faqs SYSTEM "faqs.dtd">
<faqs title="Exult" changed="03 Septembre 2001(GMT)">
	<section title="Changes to the FAQ">
		<faq name="03092001">
			<question>- 03 Septembre 2001</question>
			<answer>
				<ul>
				<li><ref1 target="latest_version"/> Version updated</li>
				<li><ref1 target="other_improvements"/> Added "close on doubleclick".</li>
				<li><ref1 target="known_issues"/> added note about stealing, killing NPCs</li>
				<li><ref1 target="compile_issues"/> added this with information on compiling in 
					Unix and the bug with the flex bundled with some Linux systems.</li>
				</ul>	
			</answer>
		</faq>
		<faq name="10082001">
			<question>- 10 August 2001</question>
			<answer>
				<ul>
				<li><ref1 target="origin_exult"/> noted praise from LB and Ken Demarest.</li>				
				<li><ref1 target="multiplayer"/> this gets asked quite often.</li>
				<li><ref1 target="whatis_snapshot"/> added some more information.</li>
				<li><ref1 target="compile_snapshot"/> made this gnereic for all the OS'.</li>
				<li><ref1 target="what_platforms"/> added OSX.</li>
				<li><ref1 target="addon_support"/> reported both as bug-free.</li>
				<li><ref1 target="other_improvements"/> added the status bars.</li>				
				<li><ref1 target="bug_report"/> not that anyone reads the FAQ anyway. But it should get
					 all the alpha testers on the right track.</li>
				</ul>	
			</answer>
		</faq>
		<faq name="19072001">
			<question>- 19 July 2001</question>
			<answer>
				<ul>
				<li>With the updated Documentation parts of the FAQ are no longer 
					necessary and thus left out. So see the <extref target="docs.php">Documentation</extref>
					for all your configuration problems</li>
				</ul>	
			</answer>
		</faq>
	</section>
	<section title="Introduction">
		<faq name="why_name_exult">
			<question>Why is it called <Exult/> - what is the meaning of this name?</question>
			<answer>
				<cite name="Jeff wrote on the Boards">
					I originally wrote it [Exult] solely for X-windows, so that's where
					the 'X' comes from. The "ult", of course, comes from Ultima. It
					was only about 6 months ago [02/29/2000] that I replaced the X code with SDL,
					which is multiplatform. Then Arthuris ported it to Win32 (and to
					BeOS). He had also ported the earlier version, but it was much harder
					to maintain that way.
				</cite>
				<cite name="Ibrahim Holtzmann">
					I'd like to point out that "exult" is also an English verb that
					means "to rejoice, to exhibit great happiness".
				</cite>
			</answer>
		</faq>
		<faq name="is_exult_free">
			<question>Is <Exult/> free ?</question>
			<answer>
				<para>
					<Exult/> is more than free: it's Free (notice the caps). <Exult/> is released
					under the GNU GPL (General Public License). This means that the source code
					for <Exult/> is freely available and you can do whatever you want with it.
					However, if you make modifications to any of <Exult/>'s components and publicly
					redistribute your work you are required to make the source freely available
					in turn. Obviously the <Exult/> team would be very grateful if any
					modifications you make are contributed back to the main code, so that
					everyone can benefit from them. If you want to work on <Exult/> just send an
					e-mail to the 
					<extref target="mailto:exult-general@lists.sourceforge.net">team</extref>.<br/>
 					More information on the GNU GPL at 
 					<extref target="http://www.gnu.org/copyleft/gpl.html"/>.
				</para>
			</answer>
		</faq>
		<faq name="origin_exult">
			<question>Does Origin support <Exult/>?</question>
			<answer>
				<para>
					First of all, Origin has been owned by EA for a long time now and from recent 
					developements it seems that Origin only exists now to maintain Ultima Online. 
					Furthermore, Origin and/or people that worked for Origin claim that the source 
					code for Ultima 7 (BG/SI) has been lost for some time.
					So there is no chance for the <Exult/> team to have a look at the actual code.
				</para>
				<para>
					Also the team tried to contact some people from Origin earlier but got no positive
					or negative response on the <Exult/> project. So far it seems that both Origin and 
					EA have decided to ignore <Exult/>.
				</para>
				<para>
					On the other hand former Origin employees contacted the team and congratulated the 
					team on their effort. Most noticeable are Lord British himself and Ken Demarest 
					(Programming Manager of Ultima 7)(hint:spell his name backwards).
				</para>
			</answer>
		</faq>
		<faq name="other_ultimas">
			<question>Will <Exult/> support other Ultimas?</question>
			<answer>
				<para>
					<Exult/> supports only Ultima 7 (BG/SI and the add-ons). It will never support
					any other Ultima nor do members of the team plan to develop something similar.
					The reasons for this are that no other Ultima is similar to Ultima 7 in the 
					internal workings and also the team is quite sick of reverse engineering a game
					allready. 
				</para>
			</answer>
		</faq>
		<faq name="multiplayer">
			<question>Will there be a multiplayer <Exult/>?</question>
			<answer>
				<para>
					No.
				</para>
				<cite name="Jeff on the Forum">
					The question is 'why?'. I continue working on <Exult/>, in large part, because 
					nobody makes games like Ultima7 anymore. While I think a multi-player game 
					would be technically interesting, I don't see the need. There are <em>lots</em> 
					of them already, and many experienced people working on new ones.
				</cite>
				<para>
					Note however that <Exult/> is open source. If you want a multiplayer U7 no one
					holds you back to code it in. 
				</para>
			</answer>
		</faq>
		<faq name="whereis_exult">
			<question>Where do I find <Exult/>?</question>
			<answer>
				<para>
					The latest official version is found on <extref target="http://exult.sourceforge.net/"/><br/>
					Daily snapshots of the Win32 binary and of the CVS source tree can be found at
					<extref target="http://exult.sourceforge.net/download.php"/>
				</para>
			</answer>
		</faq>
		<faq name="whatis_snapshot">
			<question>What is a snapshot? Are these screenshots or what?</question>
			<answer>
			    <para>
			    	Bugs and not yet implemented features in <Exult/> get fixed almost daily in the code.
			    	A release is very time consuming that's why there are so few.
			    </para>	
			    <para>
					The snapshot is the newest source code of the program. It is updated almost
					daily, sometimes twice a day. There is information on how to build your
					own binary in the source but there is also the newest pre-compiled Windows binary.
					If you there is no new one this means that either there were no changes to the code
					or the source failed to compile.
				</para>
				<para>
					Also this FAQ mainly addresses the snapshots as people use them and ask question.
				</para>
			</answer>
		</faq>
		<faq name="compile_snapshot">
			<question>How do I compile a source code snapshot for my OS?</question>
			<answer>
				<para>
					The source code snapshots contain a file called "README.OS" (like Readme.win32, 
					Readme.MacOS) that explains everything.
				</para>
			</answer>
		</faq>
		<faq name="latest_version">
			<question>What is the latest version of <Exult/>?</question>
			<answer>
				<para>
					The current official release is V0.94 Alpha5. See also <ref target="whereis_exult"/>
					to learn where to get the latest version.
				</para>
				<para>
					To find out which version you are running, press <key>v</key> while in game.
				</para>
			</answer>
		</faq>
		<faq name="what_platforms">
			<question>On what platform does <Exult/> run?</question>
			<answer>
				<para>
					<Exult/> should be able to be compiled (with minor modifications) on
					any platform that SDL supports. Right now the source can be compiled
					in Linux/i386, Linux/Alpha, MacOS, OSX, OpenBSD, FreeBSD, Solaris, BeOS and 
					Win32 (Windows 9x/ME/NT/2000).
				</para>
			</answer>
		</faq>
	</section>
  	<section title="Exult and Ultima 7">
		<faq name="u7_needed">
			<question>Do I need Ultima 7?</question>
			<answer>
				<para>
					Yes. <Exult/> won't work without the original files.
				</para>
			</answer>
		</faq>
		<faq name="u7_versions">
			<question>Does <Exult/> work on all versions of the game?</question>
			<answer>
				<para>
					It seems to run most of the available versions of the game. The most common
					ones nowadays with the included Add-Ons (Forge of Virtue and Silver Seed) 
					runs for sure.
				</para>
				<para>
					However there are reported problems with the localized versions of the
					game (French, German and Spanish). Conversation threads don't seem to skip to the
					next line in the proper places and therefore are unreadable in some cases. SI
					was only published in English so no localization problems with that one.
				</para>
				<para>
					V0.91 Alpha2 adds fixes for the french version, which should work now.
					No work has been done for the german version, due to lack of testers. If
					you have the German or Spanish version, and want it to run, contact us.
				</para>
			</answer>
		</faq>
		<faq name="si_support">
			<question>How about Serpent Isle?</question>
			<answer>
				<para>
					The team is working on it. It is not yet fully playable but you can walk around,
					talk to people, finish a lot of quests... Plotwise you will
					get quite far but you certainly won't be able to play through it yet.
				</para>
				<para>
					Old quotes on this topic from the time when SI wasn't playable at all in <Exult/>.
				</para>
				<cite name="Colourless">
					I can't say much about the what will happen except that a completely
					working Serpent Isle will be an annoying task to complete. It is
					close to BG in some ways, but very different in others. 
				</cite>
